spring.application.name=HomeAPP

# Default DB (local dev fallback): persistent H2
spring.datasource.url=jdbc:h2:file:./data/homeappdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Geoapify
geoapify.api-key=7aa2f88d19d7416988f9da9e123b5729
geoapify.map-tile-url=https://maps.geoapify.com/v1/tile/carto/{z}/{x}/{y}.png?&apiKey=${geoapify.api-key}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server
server.port=8080
